# Generated by Django 4.2 on 2023-04-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_agent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='Advisor',
        ),
    ]
