# Generated by Django 4.2 on 2023-04-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_case_advocate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
