# Generated by Django 4.2 on 2023-04-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_case_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestions',
            name='advocate_id',
        ),
        migrations.AddField(
            model_name='suggestions',
            name='advisor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.advisor'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/profile_pic')),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.case')),
            ],
        ),
        migrations.CreateModel(
            name='QndA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reply', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.advisor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advocate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.advocate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
