# Generated by Django 4.2 on 2023-04-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_suggestions_advocate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnda',
            name='advisor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.advisor'),
        ),
    ]
