# Generated by Django 4.2 on 2023-05-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='regno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
