# Generated by Django 4.2 on 2023-05-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_advocate_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='public_pro',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
