# Generated by Django 4.2 on 2023-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_public_pro_advocate_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='file',
            field=models.FileField(null=True, upload_to='media/profile_pic'),
        ),
    ]
