# Generated by Django 4.2 on 2023-05-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_case_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
